FROM node:20-slim

WORKDIR /usr/src/app

COPY package*.json ./

# 'apt-get update' es necesario para actualizar la lista de paquetes
# 'apt-get install -y openssl' instala la librería libssl necesaria para Prisma
RUN apt-get update -y && apt-get install -y openssl

RUN npx prisma generate
RUN npm install

# No copiamos todo el código ni lo compilamos aquí,
# ya que lo montaremos como volumen y usaremos ts-node-dev.

EXPOSE 4000

# El comando se ejecutará a través de docker-compose con el volumen montado
CMD ["npm", "run", "dev"]
