FROM node:20-slim

WORKDIR /usr/src/app

COPY package*.json ./
COPY prisma ./prisma/ 

RUN apt-get update -y && apt-get install -y openssl
COPY prisma ./prisma/ 
RUN npm install
RUN npx prisma generate

# No copiamos todo el código ni lo compilamos aquí,
# ya que lo montaremos como volumen y usaremos ts-node-dev.

EXPOSE 4000

# El comando se ejecutará a través de docker-compose con el volumen montado
CMD ["npm", "run", "dev"]
