services:
  api:
    build:
      context: .
      target: deps # Usará la etapa 'deps' que ya tiene Infisical si usaste mi Dockerfile anterior
    ports:
      - "4000:4000"
    # IMPORTANTE: Eliminamos 'env_file'
    command: npm run dev
    volumes:
      - .:/usr/src/app 
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
      # Al poner solo el nombre, Docker busca la variable en tu terminal (inyectada por Infisical)
      - DATABASE_URL=postgresql://app_user:app_password@db:5432/my_app_db
      - REDIS_HOST=redis # O la variable que uses para Redis
      - JWT_SECRET
      - FRONTEND_URL=${FRONTEND_URL:-http://localhost:4321}
      - EMAIL_USER=${EMAIL_USER}
      - EMAIL_PASS=${EMAIL_PASS}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - BREVO_ACTIVE=${BREVO_ACTIVE:-false}
      # Puedes añadir aquí cualquier otra variable que tengas en Infisical
      # --- LÍNEAS NUEVAS PARA NEW RELIC ---
      - NEW_RELIC_APP_NAME
      - NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_ENABLED=true
      - NEW_RELIC_LOG_LEVEL
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_ATTRIBUTES_INCLUDE="utils.prisma.*"

    depends_on:
      db:
        condition: service_healthy 
      redis:
        condition: service_healthy
    networks:
      - coolify
  db:
    image: postgres:15
    ports:
      - "5433:5432"
    environment:
      # Estos valores pueden ser fijos en dev o venir de Infisical también
      - POSTGRES_USER=${POSTGRES_USER:-app_user}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-app_password}
      - POSTGRES_DB=${POSTGRES_DB:-my_app_db}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U $${POSTGRES_USER} -d $${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s
    networks:
      - coolify
  redis:
    image: redis:7
    ports:
      - "6378:6379"
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 5
    networks:
      - coolify
volumes:
  postgres_data: