services:
  api:
    build:
      context: .
      #dockerfile: Dockerfile.dev
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      # **IMPORTANTE:** Este nombre aparecerá en el Dashboard de SigNoz
      - OTEL_SERVICE_NAME=SecureAuthApi
      # Esto permite que el contenedor se conecte al host (donde está SigNoz corriendo)
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4318/v1/traces
      # Para la instrumentación automática
      - NODE_OPTIONS=-r ./dist/tracer.js 
      # Ajusta la ruta a tu archivo tracer.js compilado
    volumes:
      - .:/usr/src/app # Monta el directorio del proyecto para la detección de cambios
      - /usr/src/app/node_modules # Evita que los node_modules locales sobrescriban los del contenedor
    depends_on:
        db:
          condition: service_healthy # 🛑 CAMBIO CRUCIAL: Esperar a que la DB esté lista para conexiones
        redis:
          condition: service_started
  db:
    image: postgres:15
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=secure_auth_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
    # 🛑 NUEVA CONFIGURACIÓN: Healthcheck
    healthcheck:
      # Comando que verifica si la base de datos está lista (usando el usuario 'user')
      test: ["CMD-SHELL", "pg_isready -U user"] 
      interval: 5s
      timeout: 5s
      retries: 5
      start_period: 10s # Tiempo inicial para que el servidor arranque
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: