services:
  api:
    build:
      context: .
      target: runner
      # Añadimos esta sección para asegurar que los args pasen del host al Dockerfile
      args:
        - INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}
        - INFISICAL_CLIENT_SECRET=${INFISICAL_CLIENT_SECRET}
        - INFISICAL_ENV=${INFISICAL_ENV}
        - INFISICAL_PROJECT_PATH=${INFISICAL_PROJECT_PATH}
        - NODE_ENV=${NODE_ENV:-production}
    ports:
      - '${PORT:-4000}:4000'
    environment:
      - DATABASE_URL
      - JWT_SECRET
      - NEW_RELIC_APP_NAME
      - NEW_RELIC_LICENSE_KEY
      - NEW_RELIC_ENABLED=true
      - NEW_RELIC_NO_CONFIG_FILE=true
      - NEW_RELIC_PRISMA_ENABLED=true
      
      # Por ESTO (Nombres estándar):
      - INFISICAL_CLIENT_ID=${INFISICAL_CLIENT_ID}
      - INFISICAL_CLIENT_SECRET=${INFISICAL_CLIENT_SECRET}
      # -----------------------

      - INFISICAL_ENV=${INFISICAL_ENV}
      - INFISICAL_PROJECT_PATH=${INFISICAL_PROJECT_PATH:-/api}
      - NODE_ENV=${NODE_ENV:-production}
      - INFISICAL_PROJECT_ID=${INFISICAL_PROJECT_ID}
      - INFISICAL_API_URL=https://app.infisical.com
    restart: always