services:
  api:
    build:
      context: .
      target: runner 
    ports:
      - "4000:4000"
    env_file:
      - .env # Carga las variables de entorno para producción
    command: npm run start:prod
    # No se definen servicios 'db' ni 'redis' aquí, ya que se conectará a servicios externos.

# Nota: No se definen 'volumes' de persistencia para la base de datos local aquí,
# ya que la base de datos y Redis serán servicios gestionados externamente.
