services:
  api:
    build: .
    ports:
      - "4000:4000"
    env_file:
      - .env
    # Variables de Entorno para OpenTelemetry
    environment:
      # **IMPORTANTE:** Este nombre aparecerá en el Dashboard de SigNoz
      - OTEL_SERVICE_NAME=SecureAuthApi
      # Esto permite que el contenedor se conecte al host (donde está SigNoz corriendo)
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://host.docker.internal:4318/v1/traces
      # Para la instrumentación automática
      - NODE_OPTIONS=-r ./dist/tracer.js 
      # Ajusta la ruta a tu archivo tracer.js compilado
    depends_on:
      - db
      - redis
  db:
    image: postgres:15
    environment:
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=secure_auth_api
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7
    ports:
      - "6379:6379"

volumes:
  postgres_data: